version: '2'
volumes:
  vol-mongo:
    driver: local
  vol-nodered:
    driver: local
services:
  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: teste
    volumes:
    - vol-mongo:/data/db:rw
    labels:
      io.rancher.scheduler.affinity:host_label: group=hosts
  balance:
    image: rancher/lb-service-haproxy:v0.9.1
    ports:
    - 2000:2000/tcp
    - 2001:2001/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: group=hosts
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  mongo-client:
    image: mongoclient/mongoclient
    environment:
      MONGO_URL: mongodb://mongo-db:27017
    links:
    - mongo-db:mongo-db
    labels:
      io.rancher.scheduler.affinity:host_label: group=hosts
  node-red:
    image: robsonsimonassi/nodered
    volumes:
    - vol-nodered:/data:rw
    links:
    - mongo-db:mongo-db
